### ISSUE TITLE
Docker-sync generated excludes are too hard

### ISSUE THREAD

**Issue by anivon** [Ph3nol/Docker-Arch#24]

**Comment by Ph3nol** [comment]
My d*** too.
😱

**Comment by anivon** [comment]
![image](https://user-images.githubusercontent.com/4992953/31441872-cbfbb0d8-ae94-11e7-9dcd-34d1f66ed3e5.png)

**Comment by anivon** [comment]
Fixed in https://github.com/Ph3nol/Docker-Arch/releases/tag/v1.18.8
